name: Build and publish NuGet package to organization

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up NuGet CLI
        uses: nuget/setup-nuget@v1

      - name: Build NuGet package
        run: nuget pack

      - name: Push NuGet package to organization
        run: nuget push ./*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }}
